{% set version = "6.4.0" %}

package:
  name: nbconvert
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbconvert/nbconvert-{{ version }}.tar.gz
  sha256: 91ff0058b45660aad4a68088041059c0d378cd53fc8aff60e5abc91bcc049353

build:
  number: 1
  skip: True  # [py<37]
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - jupyter-nbconvert = nbconvert.nbconvertapp:main
    - jupyter-dejavu = nbconvert.nbconvertapp:dejavu_main

requirements:
  build:
    - python                               # [build_platform != target_platform]
    - cross-python_{{ target_platform }}   # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - mistune >=0.8.1,<2
    - jinja2 >=2.4
    - pygments >=2.4.1
    - traitlets >=5.0
    - jupyter_core
    - nbformat >=4.4
    - entrypoints >=0.2.2
    - bleach
    - pandocfilters >=1.4.1
    - testpath
    - defusedxml
    - pandoc >=1.12.1  # [x86]
    - nbclient >=0.5.0,<0.6.0
    - jupyterlab_pygments
  run_constrained:
    - pyppeteer ==0.2.6

test:
  imports:
    - nbconvert
    - nbconvert.exporters
    - nbconvert.filters
    - nbconvert.postprocessors
    - nbconvert.preprocessors
    - nbconvert.resources
    - nbconvert.tests
    - nbconvert.utils
    - nbconvert.writers
  source_files:
    - nbconvert/tests/files/notebook1.ipynb

  commands:
    - jupyter nbconvert --version
    - jupyter dejavu --version
    - jupyter nbconvert --help
    - jupyter dejavu --help
    - jupyter nbconvert nbconvert/tests/files/notebook1.ipynb --to html

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Converting Jupyter Notebooks
  description: |
    The nbconvert tool, jupyter nbconvert, converts notebooks to various other
    formats via Jinja templates. The nbconvert tool allows you to convert an
    .ipynb notebook file into various static formats.
  doc_url: https://nbconvert.readthedocs.org/
  dev_url: https://github.com/jupyter/nbconvert

extra:
  recipe-maintainers:
    - jakirkham
    - mpacer
    - minrk
    - pelson
    - takluyver
    - mseal
    - blink1073
    - ocefpaf
    - jasongrout
