{% set version = "5.4.1" %}

package:
  name: nbconvert
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbconvert/nbconvert-{{ version }}.tar.gz
  sha256: 302554a2e219bc0fc84f3edd3e79953f3767b46ab67626fdec16e38ba3f7efe4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python
  entry_points:
    - jupyter-nbconvert = nbconvert.nbconvertapp:main

requirements:
  build:
    - python
    - pip
  run:
    - mistune >=0.8.1
    - jinja2
    - pygments
    - traitlets >=4.2
    - jupyter_core
    - nbformat >=4.4
    - entrypoints >=0.2.2
    - bleach
    - pandocfilters >=1.4.1
    - testpath
    - defusedxml
    - pandoc >=1.12.1,<2.0.0

test:
  imports:
    - nbconvert
    - nbconvert.exporters
    - nbconvert.filters
    - nbconvert.postprocessors
    - nbconvert.preprocessors
    - nbconvert.resources
    - nbconvert.tests
    - nbconvert.utils
    - nbconvert.writers
  source_files:
    - nbconvert/tests/files/notebook1.ipynb

  commands:
    - jupyter nbconvert --help
    - jupyter nbconvert nbconvert/tests/files/notebook1.ipynb

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  summary: 'Converting Jupyter Notebooks'
  description: |
    The nbconvert tool, jupyter nbconvert, converts notebooks to various other
    formats via Jinja templates. The nbconvert tool allows you to convert an
    .ipynb notebook file into various static formats.
  doc_url: http://nbconvert.readthedocs.org/
  dev_url: https://github.com/jupyter/nbconvert

extra:
  recipe-maintainers:
    - jakirkham
    - mpacer
    - minrk
    - pelson
    - takluyver
    - mseal
    - blink1073
    - ocefpaf
