# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 7.16.6
  min_pandoc: 2.9.2
  max_pandoc: 4.0.0
  pytest_args: -k "not (convert_full_qualified_name or post_processor)"
  cov_fail_under: 71

recipe:
  name: nbconvert-meta
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/n/nbconvert/nbconvert-${{ version }}.tar.gz
  sha256: 576a7e37c6480da7b8465eefa66c17844243816ce1ccc372633c6b71c3c0f582

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: nbconvert
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("nbconvert-core", exact=True) }}
        - ${{ pin_subpackage("nbconvert-pandoc", exact=True) }}
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - nbconvert
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - jupyter nbconvert --version
          - jupyter dejavu --version
          - jupyter nbconvert --help
          - jupyter dejavu --help

  - package:
      name: nbconvert-core
    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
      python:
        entry_points:
          - jupyter-dejavu = nbconvert.nbconvertapp:dejavu_main
          - jupyter-nbconvert = nbconvert.nbconvertapp:main
    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling >=1.5
        - pip
      run:
        - beautifulsoup4
        - bleach-with-css !=5.0.0
        - defusedxml
        - importlib-metadata >=3.6
        - jinja2 >=3.0
        - jupyter_core >=4.7
        - jupyterlab_pygments
        - markupsafe >=2.0
        - mistune >=2.0.3,<4
        - nbclient >=0.5.0
        - nbformat >=5.7
        - packaging
        - pandocfilters >=1.4.1
        - pygments >=2.4.1
        - python >=${{ python_min }}
        - traitlets >=5.1
      run_constraints:
        - pandoc >=${{ min_pandoc }},<${{ max_pandoc }}
        - ${{ pin_subpackage("nbconvert", exact=True) }}
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - nbconvert
            - nbconvert.exporters
            - nbconvert.filters
            - nbconvert.postprocessors
            - nbconvert.preprocessors
            - nbconvert.resources
            - nbconvert.utils
            - nbconvert.writers
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - jupyter nbconvert --version
          - jupyter dejavu --version
          - jupyter nbconvert --help
          - jupyter dejavu --help

  - package:
      name: nbconvert-qtpdf
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("nbconvert-core", exact=True) }}
        - pyqtwebengine >=5.5
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - nbconvert
      - files:
          source:
            - tests/files/notebook1.ipynb
        requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - jupyter nbconvert --version
          - jupyter dejavu --version
          - jupyter nbconvert --help
          - jupyter dejavu --help
          - if: linux
            then:
              - export DISPLAY=localhost:1.0
              - xvfb-run -a jupyter nbconvert tests/files/notebook1.ipynb --to qtpdf
            else:
              - jupyter nbconvert tests/files/notebook1.ipynb --to qtpdf
    about:
      license: BSD-3-Clause
      license_file: LICENSE
      description: nbconvert with extra packages for browser-based PDF generation
      homepage: https://jupyter.org
      repository: https://github.com/jupyter/nbconvert
      documentation: https://nbconvert.readthedocs.org

  - package:
      name: nbconvert-pandoc
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("nbconvert-core", exact=True) }}
        # the pin is handled by the `run_constrained` in nbconvert-core
        - pandoc
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - nbconvert
      - files:
          recipe:
            - check_pandoc.py
        requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - jupyter nbconvert --version
          - jupyter dejavu --version
          - jupyter nbconvert --help
          - jupyter dejavu --help
          - python check_pandoc.py ">=${{ min_pandoc }}" "<${{ max_pandoc }}"
    about:
      license: BSD-3-Clause
      license_file: LICENSE
      description: nbconvert with extra packages for pandoc-based outputs
      homepage: https://jupyter.org
      repository: https://github.com/jupyter/nbconvert
      documentation: https://nbconvert.readthedocs.org

  - package:
      name: nbconvert-webpdf
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("nbconvert-core", exact=True) }}
        - playwright-python
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - nbconvert
      - files:
          source:
            - tests/files/notebook1.ipynb
        requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - if: linux
            then:
              - export DISPLAY=localhost:1.0
          - jupyter nbconvert --version
          - jupyter dejavu --version
          - jupyter nbconvert --help
          - jupyter dejavu --help
          - playwright install chromium
          - jupyter nbconvert tests/files/notebook1.ipynb --to webpdf
    about:
      license: BSD-3-Clause
      license_file: LICENSE
      description: nbconvert with extra packages for browser-based PDF generation
      homepage: https://jupyter.org
      repository: https://github.com/jupyter/nbconvert
      documentation: https://nbconvert.readthedocs.org

  - package:
      name: nbconvert-all
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("nbconvert-core", exact=True) }}
        - ${{ pin_subpackage("nbconvert-qtpdf", exact=True) }}
        - ${{ pin_subpackage("nbconvert-webpdf", exact=True) }}
        - ${{ pin_subpackage("nbconvert", exact=True) }}
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports:
            - nbconvert
      - files:
          source:
            - pyproject.toml
            - tests/
        requirements:
          run:
            - coverage
            - flaky
            - ipykernel
            - ipywidgets >=7.9.0
            - pip
            - pytest-dependency
            - python ${{ python_min }}.*
        script:
          - jupyter nbconvert --version
          - jupyter dejavu --version
          - jupyter nbconvert --help
          - jupyter dejavu --help
          - if: linux
            then:
              - xvfb-run -a coverage run --branch --source=nbconvert -m pytest -vv ${{ pytest_args }}
              - coverage report --show-missing --skip-covered --fail-under=${{ cov_fail_under }}
            else:
              - pytest -vv ${{ pytest_args }}
    about:
      license: BSD-3-Clause
      license_file: LICENSE
      description: nbconvert with all optional packages
      homepage: https://jupyter.org
      repository: https://github.com/jupyter/nbconvert
      documentation: https://nbconvert.readthedocs.org

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Converting Jupyter Notebooks
  description: |
    The nbconvert tool, jupyter nbconvert, converts notebooks to various other
    formats via Jinja templates. The nbconvert tool allows you to convert an
    .ipynb notebook file into various static formats.
  homepage: https://jupyter.org
  repository: https://github.com/jupyter/nbconvert
  documentation: https://nbconvert.readthedocs.org

extra:
  feedstock-name: nbconvert
  recipe-maintainers:
    - jakirkham
    - mpacer
    - minrk
    - pelson
    - takluyver
    - mseal
    - blink1073
    - ocefpaf
    - jasongrout
    - bollwyvl
    - martinRenou
