travis:
  secure:
    BINSTAR_TOKEN: EP2GIi3StzmcHn3dGKFDnxb9SCIa6mhBKew/dqBRuqL8MdFYWwzLTI6UX4H2O9MNPHdAygVgX31iGD+VHnAfRtT5Hf2oo+jOHI6crAUdAd6MJp2YDabvP0v/rkU9bTH9i/cfqTFCSb8IlqYZgXjfX9OqSt3p0fW/yhJ0eDus48Sq3tUAUCPY9aKEhLCO4tAU/hhD5jBjL6gCSHe4/6tq4lIYo41+8UzKTFsi1zwzffNUldFRR4aEQy3k+fkKQXsr9afxKk2l060ih/D6BCVc1RDkroYTq5IrMHOb76exzCM2luhtIqYQeHjNa59fRIYGe6KRppDkwYorUOcY8rwXQBOTMjLJJXy2WCsVJao/CCla2Ibpjsuod4A3oWzXO1YI5jvVeOahpQiWtCqwXEdlVcRqUQZHgbj/EnrCB09r3BAtU4fG8EW07A5Dit/uHMH/UoGIZEilSE/FQPbcOiHY+BAoG9n0rm7wjK7iZIOraFX3yrtnVZDpYnC1TDXcNrKxUKmfrCoplnGstdREH88yafN6tUgpfYNzb8gZit6U1zeURtdCRETzq3sRYHk8VCBfIjEQXyToXwAa/6yAE55nZgvpUut66FBq6DPOqJoCuBx+ENw6DboSlpBcb/fgfOG71tv8L+VmeRTgcCtwpFvw8rc8h9xK49yF2StS/qoOK58=
appveyor:
  secure:
    BINSTAR_TOKEN: ZmCz+N4XnJqvdWAZXJj0Op2A3trfBxuB4aW2DvYuwas4Z/Ae7HwbcqsrlP77mZ22
